---

# OMD-Client Role - add system to OMD
 - src: https://github.com/Panxatony/panxatony.omd-client.git
   path: roles/

# FreeIPA-Client Role - add system to FreeIPA
 - src: https://github.com/Panxatony/panxatony.freeipa-client.git
   path: roles/

# FreeIPA Role - install FreeIPA
 - src: https://github.com/Panxatony/panxatony.freeipa.git
   path: roles/

# Kibana Role - install Kibana
 - src: https://github.com/Panxatony/panxatony.elk-kibana.git
   path: roles/

# ElasticSearch Role - install ElasticSearch
 - src: https://github.com/Panxatony/panxatony.elk-elastic.git
   path: roles/

# ELK Common Role - install ELK Common
 - src: https://github.com/Panxatony/panxatony.elk-common.git
   path: roles/

# NTP Role - Config NTP 
 - src: https://github.com/Panxatony/panxatony.ntp.git
   path: roles/

# CentOS Base Role 
 - src: https://github.com/Panxatony/panxatony.el-common.git
   path: roles/

# Logstash Role 
 - src: https://github.com/Panxatony/panxatony.logstash.git
   path: roles/

# Nginx Role 
 - src: https://github.com/Panxatony/panxatony.nginx.git
   path: roles/

# OMD Distro
 - src: sfromm.omdistro

# Gitlab Role 
 - src: https://github.com/Panxatony/panxatony.gitlab.git
   path: roles/

