---
- hosts: freeipa-server
  become: yes
  become_user: root

#prompt for password
  vars_prompt:

  - name: "freeipa_password"
    prompt: "Enter FreeIPA admin user password"
    private: yes

  - name: "freeipa_directory_manager_password"
    prompt: "Enter FreeIPA Directory Manager password"
    private: yes

# execute roles
  roles:
    - panxatony.ntp
    - panxatony.freeipa
