---
- hosts: elk-server
  #become: yes
  #become_user: root
  gather_facts: true

  roles:
    - panxatony.el-common
    - panxatony.ntp
    - panxatony.freeipa-client
    - panxatony.elk-common
    - panxatony.nginx
    - panxatony.elk-elastic
    - panxatony.elk-kibana
    - panxatony.logstash
    - panxatony.omd-client
