---
- hosts: omd-server
  become: yes
  become_user: root
  gather_facts: true

  #vars_files:
  #  - vars.yml

  roles:
   - panxatony.el-common
   - panxatony.ntp
   - panxatony.freeipa-client
 #  - sfromm.omdistro
